Repository band-its/band.it, pull requests merged in 2019-03, with the labels that each got.

#4 [#164007384] Backend microservice
  .codecov.yml
  .gitignore
  .travis.yml
  README.md
  build.gradle
  config/Dockerfile
  config/build.gradle
  config/src/main/java/com/bandit/config/ConfigApplication.java
  config/src/main/java/com/bandit/config/SecurityConfig.java
  config/src/main/resources/application.yml
  config/src/main/resources/shared/application.yml
  config/src/main/resources/shared/registry.yml
  config/src/main/resources/shared/ui-service.yml
  config/src/test/java/com/bandit/config/ConfigApplicationTests.java
  docker-compose.dev.yml
  docker-compose.yml
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  registry/Dockerfile
  registry/build.gradle
  registry/src/main/java/com/bandit/registry/RegistryApplication.java
  registry/src/main/resources/bootstrap.yml
  registry/src/test/java/com/bandit/registry/RegistryApplicationTests.java
  registry/src/test/resources/bootstrap.yml
  settings.gradle
  ui-service/Dockerfile
  ui-service/build.gradle
  ui-service/src/main/java/com/bandit/uiservice/UiServiceApplication.java
  ui-service/src/main/resources/bootstrap.yml
  ui-service/src/main/resources/static/index.html
  ui-service/src/test/java/com/bandit/uiservice/UiServiceApplicationTests.java
  ui-service/src/test/resources/bootstrap.yml
Labels: enhancement

#6 [#164007384] Frontend module for Angular+Boostrap web app
  .gitignore
  .travis.yml
  README.md
  frontend/.editorconfig
  frontend/.gitignore
  frontend/README.md
  frontend/angular.json
  frontend/build.gradle
  frontend/e2e/protractor.conf.js
  frontend/e2e/src/app.e2e-spec.ts
  frontend/e2e/src/app.po.ts
  frontend/e2e/tsconfig.e2e.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/assets/.gitkeep
  frontend/src/browserslist
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
  frontend/src/favicon.ico
  frontend/src/index.html
  frontend/src/karma.conf.js
  frontend/src/main.ts
  frontend/src/polyfills.ts
  frontend/src/styles.css
  frontend/src/test.ts
  frontend/src/tsconfig.app.json
  frontend/src/tsconfig.spec.json
  frontend/src/tslint.json
  frontend/tsconfig.json
  frontend/tslint.json
  settings.gradle
  ui-service/build.gradle
  ui-service/src/main/resources/static/index.html
Labels: enhancement

#7 [#164523145] Main div content with footer
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/content/content.component.css
  frontend/src/app/content/content.component.html
  frontend/src/app/content/content.component.spec.ts
  frontend/src/app/content/content.component.ts
  frontend/src/app/footer/footer.component.css
  frontend/src/app/footer/footer.component.html
  frontend/src/app/footer/footer.component.spec.ts
  frontend/src/app/footer/footer.component.ts
  frontend/src/styles.css
Labels: feature, good first issue

#11 Created module for layout
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/layout/bands/bands.component.css
  frontend/src/app/layout/bands/bands.component.html
  frontend/src/app/layout/bands/bands.component.spec.ts
  frontend/src/app/layout/bands/bands.component.ts
  frontend/src/app/layout/footer/footer.component.css
  frontend/src/app/layout/footer/footer.component.html
  frontend/src/app/layout/footer/footer.component.spec.ts
  frontend/src/app/layout/footer/footer.component.ts
  frontend/src/app/layout/homepage/homepage.component.css
  frontend/src/app/layout/homepage/homepage.component.html
  frontend/src/app/layout/homepage/homepage.component.spec.ts
  frontend/src/app/layout/homepage/homepage.component.ts
  frontend/src/app/layout/main-layout.module.ts
  frontend/src/app/layout/nav/nav.component.css
  frontend/src/app/layout/nav/nav.component.html
  frontend/src/app/layout/nav/nav.component.spec.ts
  frontend/src/app/layout/nav/nav.component.ts
  frontend/src/app/layout/sign-in/sign-in.component.css
  frontend/src/app/layout/sign-in/sign-in.component.html
  frontend/src/app/layout/sign-in/sign-in.component.spec.ts
  frontend/src/app/layout/sign-in/sign-in.component.ts
  frontend/src/app/layout/sign-up/sign-up.component.css
  frontend/src/app/layout/sign-up/sign-up.component.html
  frontend/src/app/layout/sign-up/sign-up.component.spec.ts
  frontend/src/app/layout/sign-up/sign-up.component.ts
  frontend/src/app/layout/songs/songs.component.css
  frontend/src/app/layout/songs/songs.component.html
  frontend/src/app/layout/songs/songs.component.spec.ts
  frontend/src/app/layout/songs/songs.component.ts
Labels: WIP, feature

#10 [#164523187] Local deployment without docker-compose
  .circleci/config.yml
  account-service/Dockerfile
  account-service/build.gradle
  account-service/src/main/resources/bootstrap.yml
  build.gradle
  config/Dockerfile
  config/build.gradle
  config/src/main/resources/application.yml
  config/src/main/resources/bootstrap.yml
  config/src/main/resources/shared/account-service.yml
  config/src/main/resources/shared/application.yml
  config/src/main/resources/shared/registry.yml
  config/src/main/resources/shared/ui-service.yml
  docker-compose.dev.yml
  frontend/src/app/app.component.spec.ts
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  registry/Dockerfile
  registry/build.gradle
  registry/src/main/resources/bootstrap.yml
  ui-service/Dockerfile
  ui-service/build.gradle
  ui-service/src/main/resources/bootstrap.yml
Labels: WIP, chore
